name: system-update-workflow

on:
  push:
    branches:
      - main

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: data-checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: init-environment
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: data-processing
        run: hugo --minify

      - name: rsync-remote
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: "/var/www/test-hugo/"
          SOURCE: "public/"
          ARGS: "-avz --delete"